run-example:
	./build/install/app/bin/app -f=json src/main/resources/file1.json src/main/resources/file2.json

run-help:
	./build/install/app/bin/app -h

build:
	./gradlew clean build

clean:
	./gradlew clean

install:
	./gradlew clean install

.PHONY: build